name: test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update
      - run: sudo apt-get install python3
      - run: pip install requirment.txt
      - run: python -m pytest
