name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update
      - run: sudo apt-get install python3
      - run: pip install -r requirment.txt
      - run: python -m pytest
